# Generated by Django 3.0.7 on 2020-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.CharField(choices=[], max_length=9),
        ),
    ]
